import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/Providers/ThemeProvider'
import Providers from '@/components/Providers/Providers'
import Navbar from '../components/shared/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={
					inter.className +
					'flex flex-col p-4 justify-center items-start h-dvh '
				}
			>
				<Providers>
					<Navbar />
					{children}
				</Providers>
			</body>
		</html>
	)
}
